export const UPDATE_EMP_SUCCESS = "UPDATE_EMP_SUCCESS";
export const UPDATE_EMP_FAILURE = "UPDATE_EMP_FAILURE";
export const FETCH_EMP_REQUEST = "FETCH_EMP_REQUESTF";
export const FETCH_EMP_SUCCESS = "FETCH_EMP_SUCCESS";
export const FETCH_EMP_FAILURE = "FETCH_EMP_FAILURE";
