export const FETCH_EMP_REQUEST = "FETCH_EMP_REQUESTF";
export const FETCH_EMP_SUCCESS = "FETCH_EMP_SUCCESS";
export const FETCH_EMP_FAILURE = "FETCH_EMP_FAILURE";

export const NEW_EMP_REQUEST = "NEW_EMP_REQUEST";
export const NEW_EMP_ERROR = "NEW_EMP_ERROR";
